<div class="panel-header">
    <span class="panel-title" ng-bind="(item ? 'Details' : 'List') + $instance.$$id"></span>
    <button type="button"
        class="close"
        ng-click="$dismiss()">
        &times;
    </button>

    <div
        ng-if="item"
        class="modal-action-bar">

        <button type="button"
            class="btn btn-primary"
            ng-click="$close(item)">
            Ok
        </button>
        <button type="button"
            class="btn btn-default"
            ng-click="$dismiss()">
            Cancel
        </button>
    </div>

</div>

<div class="panel-body">

    <div ng-if="item">
        <h4>Details</h4>

        <form name="itemForm"
            class="form-horizontal">
            <div class="form-group"
                ng-repeat="col in itemCols" >
                <label class="col-sm-4 control-label"
                    ng-bind="col">
                </label>
                <div class="col-sm-8">
                    <input ng-model="item.cells[col]"
                        required
                        class="form-control" />
                </div>
            </div>
        </form>

        <label>
            <input type="checkbox" ng-model="context.blocked" name="blocking" required />
            Bloquer la fermeture
        </label>

        <hr>
        <h4>Sub-items</h4>
        <br/>
    </div>

    <div class="items">
        <table class="table items-table"
            ev-fixed-headers rows="data.rows">
            <thead>
                <tr>
                    <th ng-repeat="col in data.cols"
                        ng-bind="col"></th>
                </tr>
            </thead>
            <tbody activable-set
                active-element="context.active">
                <tr ng-repeat="row in data.rows"
                    activable="row">
                    <td ng-repeat="col in data.cols" ng-bind="row.cells[col]"></td>
                </tr>
            </tbody>
        </table>

        <div class="items-inline">
            <div ng-repeat="row in data.rows"
                ng-class="{active: context.active == row}">
                <div ng-bind="row.cells.Name"
                    ng-click="context.active = row">
                </div>
            </div>
        </div>
    </div>
</div>
