<div class="modal-header">
    <button type="button"
        class="close"
        ng-click="$dismiss()">
        &times;
    </button>
    <h3 class="modal-title">Modal sample</h3>
</div>

<div class="modal-body">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut tincidunt massa. Nullam volutpat consequat erat. Vivamus non felis sed felis mattis rutrum. Integer libero mi, egestas non bibendum a, laoreet eget nibh. Phase.</p>
</div>

<div class="modal-footer">
    <button class="btn btn-default" ng-click="$dismiss()">
        Fermer
    </button>
</div>
