<div class="lisette-module-topbar lisette-module-actionbar">
    <button
        class="btn btn-primary"
        ng-click="tab1ctrl.test()">
        Primary button
    </button>
    <button
        class="btn btn-default">
        Default button
    </button>
    <div class="divider"></div>
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Dropdown button
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li><a>test1</a></li>
            <li><a>test2</a></li>
            <li><a>test3</a></li>
            <li><a>test4</a></li>
        </ul>
    </div>
</div>

<div class="lisette-module-body spaced">

    <div class="btn-group">
        <button type="button" class="btn btn-default btn-lg dropdown-toggle" data-toggle="dropdown">
            Notify
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li>
                <a href="#"
                    ng-click="notify(0)">
                    SUCCESS
                </a>
            </li>
            <li>
                <a href="#"
                    ng-click="notify(1)">
                    ERROR
                </a>
            </li>
            <li>
                <a href="#"
                    ng-click="notify(2)">
                    INFO
                </a>
            </li>
            <li>
                <a href="#"
                    ng-click="notify(3)">
                    WARNING
                </a>
            </li>
        </ul>
    </div>

    <hr>

    <div class="btn-group">
        <button type="button" class="btn btn-default btn-lg dropdown-toggle" data-toggle="dropdown">
            Open middle panel
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li>
                <a href="#"
                    ng-click="openMiddlePanel('small')">
                    Middle, small
                </a>
            </li>
            <li>
                <a href="#"
                    ng-click="openMiddlePanel()">
                    Middle, default
                </a>
            </li>
            <li>
                <a href="#"
                    ng-click="openMiddlePanel('big')">
                    Middle, big
                </a>
            </li>
            <li>
                <a href="#"
                    ng-click="openMiddlePanel('error')">
                    Middle, error
                </a>
            </li>
        </ul>
    </div>

    <hr>

    <div class="btn-group">
        <button type="button" class="btn btn-default btn-lg dropdown-toggle" data-toggle="dropdown">
            Open right panel
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li>
                <a href="#"
                    ng-click="openRightPanel()">
                    No push
                </a>
            </li>
            <li>
                <a href="#"
                    ng-click="openRightPanel(true)">
                    Push
                </a>
            </li>
        </ul>
    </div>

</div>
