<div class="lisette-module-topbar lisette-module-actionbar">
    <button
        class="btn btn-primary">
        Primary button
    </button>
    <button
        class="btn btn-default">
        Default button
    </button>
    <div class="divider"></div>
    <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Dropdown button
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li><a>test1</a></li>
            <li><a>test2</a></li>
            <li><a>test3</a></li>
            <li><a>test4</a></li>
        </ul>
    </div>
</div>

<div class="lisette-module-body spaced">

    <pre><code ng-bind="context.selectedFilters | json"></code></pre>

</div>
