<div class="modal-header">
    <button type="button" class="close" ng-click='$dismiss()'>
        &times;
    </button>
    <h3 class="modal-title">Traductions</h3>
</div>

<div class="modal-body">
    <div ng-repeat="currTranslationKey in translationsList | filter:filterTranslation">
        <span>{{ currTranslationKey.key }}</span>

        <div class="form-group" ng-repeat="currTranslation in currTranslationKey.translations" >
            <label class="col-sm-1 control-label" for="name">{{ currTranslation.lang }}</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" ng-model="currTranslation.value">
                <div class="error">Champs obligatoire</div>
            </div>
            <button ng-click="updateTranslation(currTranslationKey.key, currTranslation)" class="btn btn-default">Update</button>
        </div>
    </div>
</div>

<div class="modal-footer">
    <button class="btn btn-default" ng-click="$close()">Fermer</button>
</div>
